### ISSUE TITLE
other sponsorship options

### ISSUE THREAD

**Issue by balupton** [dropseed/onepercentdev#17]
Adding these would be great, as sponsoring individuals is subject to celebrity bias and the pareto principle

https://www.stackaid.us/
https://www.paydevs.com/

prior work was https://flossbank.com/ however that has shut down

**Comment by davegaeddert** [comment]
Sorry I'm slow to this — looks like both of these are in beta? I'd be happy to add them if that changes (and agree with the reasoning to have more)!
